# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prorest7.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Prorest(object):
    def setupUi(self, Prorest):
        Prorest.setObjectName("Prorest")
        Prorest.resize(818, 598)
        Prorest.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(151, 45, 219, 252), stop:1 rgba(72, 151, 183, 252));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 134, 213, 227), stop:0.994737 rgba(194, 255, 135, 252));")
        self.centralwidget = QtWidgets.QWidget(Prorest)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 781, 541))
        self.tabWidget.setStyleSheet("font: 75 10pt \"Garamond\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(111, 39, 186, 241), stop:0.994737 rgba(170, 20, 119, 209));\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.break_bg = QtWidgets.QLabel(self.tab)
        self.break_bg.setGeometry(QtCore.QRect(-6, -25, 781, 571))
        self.break_bg.setText("")
        self.break_bg.setPixmap(QtGui.QPixmap("../Python/BG/ThinkstockPhotos-489763838-e1490767826261.jpg"))
        self.break_bg.setObjectName("break_bg")
        self.break_btn = QtWidgets.QPushButton(self.tab)
        self.break_btn.setGeometry(QtCore.QRect(290, 290, 191, 61))
        self.break_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(45, 219, 182, 252), stop:1 rgba(209, 255, 137, 252));\n"
"font: 75 14pt \"Berlin Sans FB Demi\";")
        self.break_btn.setObjectName("break_btn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.music_bg = QtWidgets.QLabel(self.tab_2)
        self.music_bg.setGeometry(QtCore.QRect(-270, -40, 1051, 581))
        self.music_bg.setText("")
        self.music_bg.setPixmap(QtGui.QPixmap("../Python/BG/maxresdefault2.jpg"))
        self.music_bg.setObjectName("music_bg")
        self.music_btn = QtWidgets.QPushButton(self.tab_2)
        self.music_btn.setGeometry(QtCore.QRect(530, 90, 191, 61))
        self.music_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(219, 200, 45, 252), stop:1 rgba(209, 255, 137, 252));\n"
"font: 75 14pt \"Berlin Sans FB Demi\";")
        self.music_btn.setObjectName("music_btn")
        self.Random_music_btn = QtWidgets.QPushButton(self.tab_2)
        self.Random_music_btn.setGeometry(QtCore.QRect(530, 200, 191, 61))
        self.Random_music_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(219, 200, 45, 252), stop:1 rgba(209, 255, 137, 252));\n"
"font: 75 14pt \"Berlin Sans FB Demi\";")
        self.Random_music_btn.setObjectName("Random_music_btn")
        self.Automated_music_btn = QtWidgets.QPushButton(self.tab_2)
        self.Automated_music_btn.setGeometry(QtCore.QRect(530, 310, 191, 61))
        self.Automated_music_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(219, 200, 45, 252), stop:1 rgba(209, 255, 137, 252));\n"
"font: 75 14pt \"Berlin Sans FB Demi\";")
        self.Automated_music_btn.setObjectName("Automated_music_btn")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(520, 20, 211, 21))
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 227), stop:0.994737 rgba(0, 0, 0, 252));\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(78, 213, 63, 227), stop:0.994737 rgba(194, 255, 135, 252));")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(500, 40, 241, 20))
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 227), stop:0.994737 rgba(0, 0, 0, 252));\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(78, 213, 63, 227), stop:0.994737 rgba(194, 255, 135, 252));")
        self.label_2.setObjectName("label_2")
        self.write_time_bar = QtWidgets.QLineEdit(self.tab_2)
        self.write_time_bar.setGeometry(QtCore.QRect(560, 390, 131, 31))
        self.write_time_bar.setText("")
        self.write_time_bar.setObjectName("write_time_bar")
        self.time_format_label = QtWidgets.QLabel(self.tab_2)
        self.time_format_label.setGeometry(QtCore.QRect(520, 440, 211, 21))
        self.time_format_label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 227), stop:0.994737 rgba(0, 0, 0, 252));\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(78, 213, 63, 227), stop:0.994737 rgba(194, 255, 135, 252));")
        self.time_format_label.setObjectName("time_format_label")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.snacks_bg = QtWidgets.QLabel(self.tab_3)
        self.snacks_bg.setGeometry(QtCore.QRect(0, 0, 781, 521))
        self.snacks_bg.setText("")
        self.snacks_bg.setPixmap(QtGui.QPixmap("../Python/BG/bread-toasted_WDGG60RQAJ.jpg"))
        self.snacks_bg.setObjectName("snacks_bg")
        self.snacks_btn = QtWidgets.QPushButton(self.tab_3)
        self.snacks_btn.setGeometry(QtCore.QRect(10, 40, 191, 61))
        self.snacks_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(45, 219, 182, 252), stop:1 rgba(209, 255, 137, 252));\n"
"font: 75 14pt \"Berlin Sans FB Demi\";")
        self.snacks_btn.setObjectName("snacks_btn")
        self.snacks_tips = QtWidgets.QLabel(self.tab_3)
        self.snacks_tips.setGeometry(QtCore.QRect(10, 170, 191, 331))
        self.snacks_tips.setStyleSheet("font: 75 12pt \"Berlin Sans FB Demi\";")
        self.snacks_tips.setObjectName("snacks_tips")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.important_bg = QtWidgets.QLabel(self.tab_4)
        self.important_bg.setGeometry(QtCore.QRect(-4, -8, 781, 531))
        self.important_bg.setText("")
        self.important_bg.setPixmap(QtGui.QPixmap("../Python/BG/woman-writing_FFSUL8TZD3.jpg"))
        self.important_bg.setObjectName("important_bg")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 781, 511))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Python/BG/books-library_6XANS2384I.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(480, 50, 251, 421))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_5, "")
        Prorest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Prorest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 21))
        self.menubar.setObjectName("menubar")
        Prorest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Prorest)
        self.statusbar.setObjectName("statusbar")
        Prorest.setStatusBar(self.statusbar)

        self.retranslateUi(Prorest)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Prorest)

    def retranslateUi(self, Prorest):
        _translate = QtCore.QCoreApplication.translate
        Prorest.setWindowTitle(_translate("Prorest", "Prorest"))
        self.break_btn.setToolTip(_translate("Prorest", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Turn on</span></p></body></html>"))
        self.break_btn.setText(_translate("Prorest", "Turn on"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Prorest", "Break reminder"))
        self.music_btn.setToolTip(_translate("Prorest", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Turn on</span></p></body></html>"))
        self.music_btn.setText(_translate("Prorest", "Turn on"))
        self.Random_music_btn.setToolTip(_translate("Prorest", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Turn on</span></p></body></html>"))
        self.Random_music_btn.setText(_translate("Prorest", "Randomize on"))
        self.Automated_music_btn.setToolTip(_translate("Prorest", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Turn on</span></p></body></html>"))
        self.Automated_music_btn.setText(_translate("Prorest", "Set music timer"))
        self.label.setText(_translate("Prorest", " Note! When you turn the music off,"))
        self.label_2.setText(_translate("Prorest", "  the current song will need to finish fully."))
        self.time_format_label.setText(_translate("Prorest", "              Format (HH:MM)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Prorest", "Relaxing songs"))
        self.snacks_btn.setToolTip(_translate("Prorest", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Turn on</span></p></body></html>"))
        self.snacks_btn.setText(_translate("Prorest", "Turn on"))
        self.snacks_tips.setText(_translate("Prorest", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Prorest", "Snacks and Drink reminder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Prorest", "Important Dates"))
        self.label_4.setText(_translate("Prorest", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Prorest", "Resources"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Prorest = QtWidgets.QMainWindow()
    ui = Ui_Prorest()
    ui.setupUi(Prorest)
    Prorest.show()
    sys.exit(app.exec_())
